nelmio_api_doc:
    documentation:
        info:
            title: Gestion aeroport API
            description: Cette API permet de gérer les opérations liées à un aéroport.
            version: 1.0.0
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
        security:
            - Bearer: []
    areas: # to filter documented areas
        path_patterns:
            - ^/api/client/login_check
            - ^/api/gerant/login_check
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
