nelmio_api_doc:
    documentation:
        info:
            title: Gestion aeroport API
            description: Cette API permet de gérer les opérations liées à un aéroport.
            version: 1.0.0
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
        security:
            - Bearer: []
    areas: # to filter documented areas
        path_patterns:
            - ^/api/client/login_check
            - ^/api/gerant/login_check
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
    # models:
    #     names:
    #         - { alias: Vol, type: App\Entity\Vol }
    #         - { alias: Client, type: App\Entity\Client }
    #         - { alias: Gerant, type: App\Entity\Gerant }
    #         - { alias: Aeroport, type: App\Entity\Aeroport }
    #         - { alias: Avion, type: App\Entity\Avion }
            

    #         # Enums
    #         - { alias: TypeVolEnum, type: App\Entity\Enum\TypeVolEnum }
    #         - { alias: StatutVolEnum, type: App\Entity\Enum\StatutVolEnum }

